name: CI with SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for SonarCloud

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ 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 }}
          SONAR_TOKEN: ${{ a2127dc228608f0e9b8f1f3ec0d6e9dea6722c44 }}
